In [5]:
import numpy as np
import datetime

In [11]:
#list의 작업 시간
li = range(1,1000000)
 
#현재 시간 저장
s = datetime.datetime.now()
print("시작 시간:", s)

#모든 요소에 10을 곱해서 list를 수정
for i in li:
    i = i*10
    
#현재 시간 저장
s = datetime.datetime.now()
print("종료 시간:", s)

시작 시간: 2023-08-07 15:25:17.591735
종료 시간: 2023-08-07 15:25:17.665371


In [13]:
ar = np.arange(1,1000000)
s = datetime.datetime.now()
print("시작 시간:", s)
ar = ar * 10
s = datetime.datetime.now()
print("종료 시간:", s)

시작 시간: 2023-08-07 15:27:18.632442
종료 시간: 2023-08-07 15:27:18.633442


In [15]:
#배열의 정보 확인
ar = np.array([1, 2, 3,])

#ar의 자료형
print(type(ar))

#ar에 저장된 요소의 자료형
print(ar.dtype) 
#일차원 배열
print(ar.ndim)
#3개의 행으로 구성
print(ar.shape)

<class 'numpy.ndarray'>
int32
1
(3,)


In [19]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
print(ar. ndim) #2
print(ar.shape) #2행 3열

2
(2, 3)


In [21]:
ar = np.arange(1, 100, 2)
print(ar)
ar = np.linspace(1, 100, num = 10) #num은 개수
print(ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [23]:
#eye - 대각선 방향으로 1을 채운 행렬
#3X3 행렬을 생성하고 대각선 방향으로 1을 채움
ar = np.eye(3)
print(ar)
#3X3 행렬을 생성하고 대각선 방향으로 1을 채우는데 기본에서 위로
ar = np.eye(3, k = 1)
print(ar)
#3X3 행렬을 생성하고 대각선 방향으로 1을 채우는데 기본에서 아래로
ar = np.eye(3, k = -1)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [27]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar)

#대각선 방향이므로 1, 5, 9
br = np.diag(ar)
print(br)

#기본 대각선에서  하나 아래로 내려가므로 4,8
cr = np.diag(ar, k=-1)
print(cr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[4 8]


In [31]:
ar = np.array([1, 2, '3']) #문자열로 배열이 생성
print(ar)

#자료형을 지정해서 생성
#정수로 배열이 생성 - 자료형 지정
ar = np.array([1, 2, '3'], dtype=np.int32) 
print(ar)

#문자열로 배열이 생성
ar = np.array([1, 2, '3'])
print(ar)

#기존 배열의 자료형을 변경해서 생성              
br = ar.astype(np.int32) 
print(br)

['1' '2' '3']
[1 2 3]
['1' '2' '3']
[1 2 3]


In [33]:
#3X3 행렬
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
#1차원으로 변환
ar = matrix.reshape(-1)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [35]:
#3X3 행렬
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)

#1차원으로 변환 : 접근 방법을 변환한 것이라서 이전과 동일한 데이터
ar = matrix.reshape(-1)
print(ar)
ar[0] = 101
print(matrix)

#복제를 해서 1차원으로 변경 - 원본과 다른 데이터를 생성
br = matrix.flatten()
print(br)
br[0]=1
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]
[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [40]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
#전체 출력
print(matrix)

#0번째 행에 1번째 열
print(matrix[0][1])

#0번째 열의 1번째 열
#0번째 행을 선택할 때는 열 인덱스를제외
print(matrix[0])

#0번째 행에 1번째 열
#0번째 열을 선택할 때는 행에 전체라고 설정을 해야 함
#행렬 구조가 있을 때 행을 먼저 선택하고 
#열을 선택하기 때문에 행은 생략할 수 없음
print(matrix[:,0])

#0번째 행부터 2번째 행 앞까지
print(matrix[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[1 4 7]
[3 6 9]


In [43]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
#전체 출력
print(matrix)


x = matrix[0][0]
print(x)
print(matrix[0][0])

#현재는 둘다 1

x = 1004
print(x)

#[행번호][열번호] 이렇게 접근하는 경우는 슬라이싱이라고 하고
#[행번호, 열번호] 이렇게 접근하는 것이 인덱싱 
#슬라이싱은 복제를 함
#인덱싱은 참조를 복사함
#참조를 복사하면 변경이 영향을 미침
print(matrix[0][0])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
1004
1


In [44]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
#전체 출력
print(matrix)

#0번 행을 인덱싱
ar = matrix[0]
br = matrix[0, ]
print(ar)
print(br)

#ar의 0번째 요소를 100으로 수정
ar[0] = 100
print(ar)
print(br)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [46]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
#전체 출력
print(matrix)


#list를 이용하는 인덱싱을 팬시 인덱싱이라고 함
cr = matrix[[0]]
#범위를 이용하는 형태를 슬라이싱이라고 함
dr = matrix[0][:]
#팬시 인덱싱과 슬라이싱은 복제를 함
#복제된 데이터를 수정해도 원본에 영향을 주지 않음
print(ar)
print(br)

cr[0, 0] = 1004
print(cr)      #[1004, 2, 3]
print(dr)      #[1, 2, 3]
print(matrix)  #[[1, 2, 3] [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[100   2   3]
[100   2   3]
[[1004    2    3]]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
ar = np.array([10, 2, 30, 3, 7 , 8 ])
br = np.array([1, 3, 5, 6 ,7, 4])

# 조건을 만족하는 ar을 찾아서 같은 위치에 있는 br의 값을 출력
print(br[ar >= 30])


# and나 or 은 true나 false를 반환함
# &나 |는 배열 전체를 내보내고
#numpy의 모든 함수는 pandas에서 가져다씀
print(br[(ar >= 30) | (ar <= 10)])

[5]
[1 3 5 6 7 4]
