In [27]:
import numpy as np
import pandas as pd

In [9]:
#인덱스 없이 0,1,2,3으로 접근하도록 생성
series1 = pd.Series([10,20,30,40])

#인덱스와 함께 생성
series2 = pd.Series([10,20,30,40], index=["one", "two", "three", "four"])
print(series1)
print(series2)

#dict를 이용해서 key는 index가 value는 vlaue가 되도록 설정
series3 = pd.Series({"태연":"소녀시대", "수지":"Miss A", "카리나":"에스파"})
print(series3)

0    10
1    20
2    30
3    40
dtype: int64
one      10
two      20
three    30
four     40
dtype: int64
태연       소녀시대
수지     Miss A
카리나       에스파
dtype: object


In [11]:
#인덱싱
#일련 번호를 가지고 접근
print(series3[0])

#인덱스를 가지고 접근
print(series3["태연"])

#일련 번호는 종료 위치가 포함되지 않음
print(series3[0:2])
#인덱스는 종료 위치가 포함됨
print(series3["태연":"카리나"])

소녀시대
소녀시대
태연      소녀시대
수지    Miss A
dtype: object
태연       소녀시대
수지     Miss A
카리나       에스파
dtype: object


In [12]:
#값들만 출력
print(series1.values)

#연산은 ndarray와 동일하게 수행되는데 values 속성의 멤버를 가지고 연산
print(series1 + 100)
print(np.sum(series1))

[10 20 30 40]
0    110
1    120
2    130
3    140
dtype: int64
100


In [15]:
s1 = pd.Series(
    {"태연":32, "수지":34, "카리나": 24})
s2 = pd.Series(
    {"태연":np.nan, "카리나":33, "수지":98})

#nan과 연산을 하면 nan
print(s1 + s2)

수지     132.0
카리나     57.0
태연       NaN
dtype: float64


In [16]:
items = {
    'code':[1,2,3,4],
    'name':['수박', '키위', '자두', '참외'],
    'price':['30000', '25000', '1500', '2000']
}

df = pd.DataFrame(items)
print(df)

   code name  price
0     1   수박  30000
1     2   키위  25000
2     3   자두   1500
3     4   참외   2000


In [18]:
print(df.index)
print(df.columns)
df.index = range(1,5)
df.columns = ['코드', '이름', '가격']
print(df)

RangeIndex(start=0, stop=4, step=1)
Index(['code', 'name', 'price'], dtype='object')
   코드  이름     가격
1   1  수박  30000
2   2  키위  25000
3   3  자두   1500
4   4  참외   2000


In [21]:
#head나 tail 함수는 데이터가 제대로 불러져 왔는지 확인할 때 사용
print(df.head())
#이 데이터로 머신러닝을 하고자 하면 머신러닝은 numpy의 ndarray로만 가능
print(type(df.values))
#데이터 분석을 하기 전에 데이터를 가져왔으면 데이터에 대한 정보를 확인
df.info()

   코드  이름     가격
1   1  수박  30000
2   2  키위  25000
3   3  자두   1500
4   4  참외   2000
<class 'numpy.ndarray'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 1 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   코드      4 non-null      int64 
 1   이름      4 non-null      object
 2   가격      4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [34]:
import numpy as np
import pandas as pd

In [46]:
items = pd.read_csv('0808Tableau 5/data/item.csv')
print(items)

   code  manufacture            name  price
0     1        korea           apple   1500
1     2        korea      watermelon  15000
2     3        korea  oriental melon   1000
3     4  philippines          banana    500
4     5        korea           lemon   1500
5     6        korea           mango    700


In [54]:
goods = pd.read_csv('./data/good.csv', header=None, names=['제품명', '개수', '가격'])
print(goods)

      제품명  개수     가격
0   apple  10   1500
1  banana   5  15000
2   melon   7   1000
3    kiwi  20    500
4   mango  30   1500
5  orange   4    700


In [41]:
goods = pd.read_csv('0808Tableau 5/data/good.csv', header=None, chunksize = 3)
print(goods)

for piece in goods:
    print(type(piece))
    print(piece)
    print()

<class 'pandas.core.frame.DataFrame'>
        0   1      2
0   apple  10   1500
1  banana   5  15000
2   melon   7   1000

<class 'pandas.core.frame.DataFrame'>
        0   1     2
3    kiwi  20   500
4   mango  30  1500
5  orange   4   700



In [48]:
goods = pd.read_csv('0808Tableau 5/data/gapminder.tsv', sep = "\t")
print(goods)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]


In [57]:
data = pd.read_csv('./0808Tableau 5/year.csv', sep = ",", encoding='cp949')
print(data)

C:\Users\user\AppData\Local\Temp\ipykernel_27076\2223419809.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('./0808Tableau 5/year.csv', sep = ",", encoding='cp949')


         자료생성년월                                             사업장명  사업자등록번호  \
0       2023-06                                        (주)니프코코리아   211814   
1       2023-06                                          신일기업(주)   201810   
2       2023-06                                         디에스디엘(주)   104811   
3       2023-06                                           (주)헤럴드   104810   
4       2023-06                                          연합뉴스(주)   102812   
...         ...                                              ...      ...   
539178  2023-06                (주)국도설비/일용/부산 사하구 다대동 리슈빌아파트 소방공사   314810   
539179  2023-06                동우개발주식회사-(일용)2023년 군산시 도시가스 보조금사업   401814   
539180  2023-06     에이치디씨랩스(주)(일용)아시아드 레이카운티 조경공사(시설물)MM23060003   120819   
539181  2023-06  （주）삼화플랜/일용/22년노후공공임대주택그린리모델링공사2-2권역(경기2)중기계설비공사   210813   
539182  2023-06  아이컴넷(주)-(일용)포스코필바라리튬솔루션 광석리튬 상업화 2공장 사무동 정보통신공사   720860   

        사업장가입상태코드 1 등록 2 탈퇴   우편번호        사업장지번상세주소           사업장도로명상세주소  \

In [58]:
matrix = np.array(range(1,16)).reshape((5,3))
print(matrix)


#행과 열을 변경
print(matrix.T)

#행과 열을 변경
print(np.transpose(matrix))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]
